### ISSUE TITLE
Installation infinitely stuck if not enough memory

### ISSUE THREAD

**Issue by jimboolio** [mailcow/mailcow-ansiblerole#38]
Playbook `main.yml` calls generate_config.sh which checks the amount of available ram, if there is less than 2097152 (of some unit) the script will get infinitely stuck at row 105 and 125 on [`generate_config.sh`](https://github.com/mailcow/mailcow-dockerized/blob/master/generate_config.sh#L105)

The play is currently like this:
```
- name: Generate mailcow.conf file
  shell: ./generate_config.sh
  environment:
    MAILCOW_HOSTNAME: "{{ mailcow__hostname }}"
    MAILCOW_TZ: "{{ mailcow__timezone }}"
    MAILCOW_BRANCH: "{{ mailcow__git_version }}"
  args:
    executable: /bin/bash
    chdir: "{{ mailcow__install_path }}"
    creates: mailcow.conf
  tags:
    - skip_ansible_lint
```

On Ansible role side I'd fix it by adding a timeout, for example like this (didn't yet test) and additionally mentioning it somewhere that the role does not support (yet) these cases where installed memory is less than x amount:
```
- name: Generate mailcow.conf file
  shell: ./generate_config.sh
  environment:
    MAILCOW_HOSTNAME: "{{ mailcow__hostname }}"
    MAILCOW_TZ: "{{ mailcow__timezone }}"
    MAILCOW_BRANCH: "{{ mailcow__git_version }}"
  args:
    executable: /bin/bash
    chdir: "{{ mailcow__install_path }}"
    creates: mailcow.conf
  tags:
    - skip_ansible_lint
  async: 60
  poll: 5
```

A proper fix would be to modify `generate_config.sh` to handle these situations without interactions.
